use crate::{subtitles::SubtitleTrack, transcripts::TranscriptRevision};

/// Formats a millisecond timestamp as an ASS timestamp (`H:MM:SS.cc`).
#[must_use]
pub fn format_ass_timestamp(value_ms: i64) -> String {
    let non_negative = value_ms.max(0);
    let hours = non_negative / 3_600_000;
    let minutes = (non_negative % 3_600_000) / 60_000;
    let seconds = (non_negative % 60_000) / 1_000;
    let centiseconds = (non_negative % 1_000) / 10;
    format!("{hours}:{minutes:02}:{seconds:02}.{centiseconds:02}")
}

fn is_translation_track_label(label: &str) -> bool {
    let l = label.trim().to_lowercase();
    let is_source = l == "main"
        || l == "speech"
        || l == "transcript"
        || l == "original"
        || l == "source"
        || l == "primary"
        || l == "default";
    !is_source
}

fn words_match_cue_text(words: &[&crate::transcripts::TimedWord], cue_text: &str) -> bool {
    if words.is_empty() {
        return false;
    }
    let cue_lower = cue_text.to_lowercase();
    words.iter().any(|w| {
        let clean_word: String = w.text().chars().filter(|c| c.is_alphanumeric()).collect();
        if clean_word.is_empty() {
            false
        } else {
            cue_lower.contains(&clean_word.to_lowercase())
        }
    })
}

/// Generates a valid ASS (Advanced `SubStation` Alpha) subtitle document from a track and optional transcript revision.
///
/// When a `revision` is provided, words falling within each cue's time range are converted
/// into ASS karaoke timing tags `{\k<cs>}` where `cs` is the word duration in centiseconds.
/// Pauses (lead-in, inter-word gaps, and lead-out) are accounted for so karaoke timing
/// stays strictly synchronized with the audio and centiseconds sum to cue duration.
#[must_use]
pub fn write_ass(track: &SubtitleTrack, revision: Option<&TranscriptRevision>) -> String {
    use std::fmt::Write;

    let mut output = String::new();
    output.push_str("[Script Info]\n");
    output.push_str("; Script generated by OneClick Subtitles Generator\n");
    output.push_str("ScriptType: v4.00+\n");
    output.push_str("PlayResX: 1920\n");
    output.push_str("PlayResY: 1080\n");
    output.push_str("ScaledBorderAndShadow: yes\n\n");

    output.push_str("[V4+ Styles]\n");
    output.push_str("Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n");
    output.push_str("Style: Default,Arial,48,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,0,2,10,10,10,1\n\n");

    output.push_str("[Events]\n");
    output.push_str("Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n");

    let is_trans_track = is_translation_track_label(track.label());

    for cue in track.cues() {
        let start_str = format_ass_timestamp(cue.start_ms());
        let end_str = format_ass_timestamp(cue.end_ms());

        let text = if is_trans_track || cue.source_id().is_some() {
            cue.text().replace('\n', "\\N")
        } else if let Some(rev) = revision {
            let words = rev.words_in_range(cue.start_ms(), cue.end_ms());
            if words.is_empty() || !words_match_cue_text(&words, cue.text()) {
                cue.text().replace('\n', "\\N")
            } else {
                let cue_dur_ms = cue.end_ms() - cue.start_ms();
                let target_cue_duration_cs = (((cue_dur_ms) + 5) / 10).max(1);

                let t_cs = |ms: i64| -> i64 {
                    let rel = (ms - cue.start_ms()).max(0);
                    (((rel) + 5) / 10).min(target_cue_duration_cs)
                };

                let lead_in_cs = t_cs(words[0].start_ms());

                let mut word_cs_list = Vec::with_capacity(words.len());
                let mut gap_cs_list = Vec::with_capacity(words.len().saturating_sub(1));

                for (idx, word) in words.iter().enumerate() {
                    let w_start_cs = t_cs(word.start_ms());
                    let w_end_cs = t_cs(word.end_ms());
                    let w_dur_cs = (w_end_cs - w_start_cs).max(1);
                    word_cs_list.push(w_dur_cs);

                    if idx + 1 < words.len() {
                        let next_start_cs = t_cs(words[idx + 1].start_ms());
                        let gap_cs = (next_start_cs - w_end_cs).max(0);
                        gap_cs_list.push(gap_cs);
                    }
                }

                let last_end_cs = t_cs(words.last().map_or(cue.end_ms(), |w| w.end_ms()));
                let mut lead_out_cs = (target_cue_duration_cs - last_end_cs).max(0);

                // Exact centisecond sum reconciliation against target_cue_duration_cs
                let total_emitted: i64 = lead_in_cs
                    + word_cs_list.iter().sum::<i64>()
                    + gap_cs_list.iter().sum::<i64>()
                    + lead_out_cs;

                if total_emitted != target_cue_duration_cs {
                    let diff = target_cue_duration_cs - total_emitted;
                    if lead_out_cs + diff >= 0 {
                        lead_out_cs += diff;
                    } else if let Some(last_word_cs) = word_cs_list.last_mut() {
                        *last_word_cs = (*last_word_cs + diff).max(1);
                    }
                }

                let mut line = String::new();
                if lead_in_cs > 0 {
                    let _ = write!(line, "{{\\k{lead_in_cs}}}");
                }

                for (idx, word) in words.iter().enumerate() {
                    let w_dur = word_cs_list[idx];
                    let _ = write!(line, "{{\\k{w_dur}}}{}", word.text());
                    if idx + 1 < words.len() {
                        let gap_dur = gap_cs_list[idx];
                        if gap_dur > 0 {
                            let _ = write!(line, "{{\\k{gap_dur}}} ");
                        } else {
                            line.push(' ');
                        }
                    }
                }

                if lead_out_cs > 0 {
                    let _ = write!(line, "{{\\k{lead_out_cs}}}");
                }

                line
            }
        } else {
            cue.text().replace('\n', "\\N")
        };

        let _ = writeln!(
            output,
            "Dialogue: 0,{start_str},{end_str},Default,,0,0,0,,{text}"
        );
    }

    output
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        ids::{AssetId, ProjectId, TranscriptRevisionId},
        subtitles::{SubtitleCue, SubtitleTrack, TrackOrigin},
        transcripts::{CompletionState, TimedWord, TranscriptRevision},
    };

    #[test]
    fn formats_ass_timestamps_correctly() {
        assert_eq!(format_ass_timestamp(0), "0:00:00.00");
        assert_eq!(format_ass_timestamp(1_500), "0:00:01.50");
        assert_eq!(format_ass_timestamp(65_430), "0:01:05.43");
        assert_eq!(format_ass_timestamp(3_661_050), "1:01:01.05");
    }

    #[test]
    fn writes_ass_without_revision() {
        let cue = SubtitleCue::new(1000, 2500, "Hello world".to_string()).unwrap();
        let track = SubtitleTrack::new("Main".to_string(), TrackOrigin::Srt, vec![cue]).unwrap();
        let ass = write_ass(&track, None);

        assert!(ass.contains("[Script Info]"));
        assert!(ass.contains("[V4+ Styles]"));
        assert!(ass.contains("[Events]"));
        assert!(ass.contains("Dialogue: 0,0:00:01.00,0:00:02.50,Default,,0,0,0,,Hello world"));
    }

    #[test]
    fn writes_ass_with_karaoke_tags_from_revision() {
        let cue = SubtitleCue::new(1000, 2700, "Word Highlight Check".to_string()).unwrap();
        let track = SubtitleTrack::new("Main".to_string(), TrackOrigin::Srt, vec![cue]).unwrap();

        let rev_id = TranscriptRevisionId::new();
        let w1 = TimedWord::new(rev_id, 0, "Word", "1.000s", "1.400s", 1000, 1400, None, None).unwrap();
        let w2 = TimedWord::new(rev_id, 1, "Highlight", "1.500s", "2.100s", 1500, 2100, None, None).unwrap();
        let w3 = TimedWord::new(rev_id, 2, "Check", "2.200s", "2.700s", 2200, 2700, None, None).unwrap();

        let rev = TranscriptRevision::new(
            ProjectId::new(),
            Some(AssetId::new()),
            1000,
            2700,
            "gemini".to_string(),
            "gemini-2.5-flash".to_string(),
            1,
            CompletionState::Completed,
            "fp".to_string(),
            1000,
            vec![w1, w2, w3],
            Vec::new(),
        ).unwrap();

        let ass = write_ass(&track, Some(&rev));
        assert!(ass.contains("Dialogue: 0,0:00:01.00,0:00:02.70,Default,,0,0,0,,{\\k40}Word{\\k10} {\\k60}Highlight{\\k10} {\\k50}Check"));
    }

    #[test]
    fn writes_ass_preserves_translation_track_text() {
        let cue = SubtitleCue::new(1000, 2700, "Xin chào thế giới".to_string()).unwrap();
        let track = SubtitleTrack::new("Vietnamese".to_string(), TrackOrigin::Srt, vec![cue]).unwrap();

        let rev_id = TranscriptRevisionId::new();
        let w1 = TimedWord::new(rev_id, 0, "Hello", "1.000s", "1.800s", 1000, 1800, None, None).unwrap();
        let w2 = TimedWord::new(rev_id, 1, "world", "1.900s", "2.700s", 1900, 2700, None, None).unwrap();

        let rev = TranscriptRevision::new(
            ProjectId::new(),
            Some(AssetId::new()),
            1000,
            2700,
            "gemini".to_string(),
            "gemini-2.5-flash".to_string(),
            1,
            CompletionState::Completed,
            "fp".to_string(),
            1000,
            vec![w1, w2],
            Vec::new(),
        ).unwrap();

        let ass = write_ass(&track, Some(&rev));
        assert!(ass.contains("Dialogue: 0,0:00:01.00,0:00:02.70,Default,,0,0,0,,Xin chào thế giới"));
        assert!(!ass.contains("Hello"));
    }
}
