import { strict as assert } from 'node:assert';
import {
  copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync,
} from 'node:fs';
import { basename, join, relative, resolve, sep } from 'node:path';

import { REPOSITORY_ROOT } from './environment.js';

/* global browser, document, getComputedStyle, window */

export const WORKFLOW_EVIDENCE_ROOT = join(REPOSITORY_ROOT, 'target', 'workflow-evidence');

export const workflowNameForJourney = (journey) => basename(journey, '.journey.js')
  .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
  .toLowerCase();

const safeSegment = (value, label) => {
  assert.match(value, /^[a-z0-9][a-z0-9-]{0,79}$/, `${label} must be a bounded slug`);
  return value;
};

export const workflowEvidenceDirectory = (workflow) => {
  const directory = resolve(WORKFLOW_EVIDENCE_ROOT, safeSegment(workflow, 'workflow'));
  const inside = relative(resolve(WORKFLOW_EVIDENCE_ROOT), directory);
  assert.ok(inside !== '' && inside !== '..' && !inside.startsWith(`..${sep}`));
  return directory;
};

/** Remove only generated evidence for one exact validated workflow. */
export const resetWorkflowEvidence = (workflow) => {
  const directory = workflowEvidenceDirectory(workflow);
  rmSync(directory, { recursive: true, force: true });
  mkdirSync(directory, { recursive: true });
  return directory;
};

const readManifest = (workflow) => {
  const path = join(workflowEvidenceDirectory(workflow), 'manifest.json');
  if (!existsSync(path)) return { schemaVersion: 1, workflow, steps: [], artifacts: [] };
  return JSON.parse(readFileSync(path, 'utf8'));
};

const writeIndex = (manifest) => {
  const directory = workflowEvidenceDirectory(manifest.workflow);
  writeFileSync(join(directory, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);
  const lines = [
    `# ${manifest.workflow}`,
    '',
    'Generated by the guarded real-binary workflow. PNGs are ordered customer-visible checkpoints;',
    '`manifest.json` records the bounded visible state and independent details captured beside them.',
    '',
  ];
  for (const step of manifest.steps) {
    lines.push(`## ${step.step}`, '', step.description, '', `![${step.step}](${step.screenshot})`, '');
  }
  if (manifest.artifacts.length > 0) {
    lines.push('## Independent artifacts', '');
    for (const artifact of manifest.artifacts) {
      lines.push(`- [${artifact.name}](${artifact.file}) — ${artifact.description}`);
    }
    lines.push('');
  }
  writeFileSync(join(directory, 'README.md'), `${lines.join('\n')}\n`);
  const workflows = readdirSync(WORKFLOW_EVIDENCE_ROOT, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && existsSync(join(WORKFLOW_EVIDENCE_ROOT, entry.name, 'manifest.json')))
    .map((entry) => {
      const record = JSON.parse(readFileSync(
        join(WORKFLOW_EVIDENCE_ROOT, entry.name, 'manifest.json'),
        'utf8',
      ));
      return { name: entry.name, steps: record.steps.length, artifacts: record.artifacts.length };
    })
    .sort((left, right) => left.name.localeCompare(right.name));
  const rootLines = [
    '# Real workflow screenshots',
    '',
    'Each folder is one non-repetitive customer workflow, captured from the guarded real desktop binary.',
    '',
    ...workflows.map(({ name, steps, artifacts }) => (
      `- [${name}](${name}/README.md) — ${steps} screenshot(s), ${artifacts} independent artifact(s)`
    )),
    '',
  ];
  writeFileSync(join(WORKFLOW_EVIDENCE_ROOT, 'README.md'), rootLines.join('\n'));
};

const visibleState = () => browser.execute(() => {
  const visible = (node) => {
    const style = getComputedStyle(node);
    const rect = node.getBoundingClientRect();
    return style.display !== 'none' && style.visibility !== 'hidden' && rect.width > 0 && rect.height > 0;
  };
  const textOf = (node) => (node.innerText || node.textContent || '').trim().replace(/\s+/g, ' ');
  return {
    viewport: [window.innerWidth, window.innerHeight],
    document: [document.documentElement.scrollWidth, document.documentElement.scrollHeight],
    horizontalOverflow: document.documentElement.scrollWidth > window.innerWidth,
    previewState: document.querySelector('[data-osg-preview]')?.getAttribute('data-osg-preview') ?? null,
    renderAdmission: document.querySelector('[data-osg-render-admission]')
      ?.getAttribute('data-osg-render-admission') ?? null,
    alerts: [...document.querySelectorAll('.error, .toast-error, [role="alert"]')]
      .filter(visible).map(textOf).filter(Boolean).slice(0, 12),
    toasts: [...document.querySelectorAll('.toast-item.live .toast')]
      .filter(visible).map(textOf).filter(Boolean).slice(-8),
    visibleText: textOf(document.body).slice(0, 4_000),
  };
});

export const captureWorkflowStep = async ({
  workflow,
  step,
  description,
  details = {},
  focusSelector = null,
}) => {
  safeSegment(step, 'step');
  assert.equal(typeof description, 'string');
  assert.ok(description.trim().length > 0, 'evidence needs a human-readable purpose');
  const directory = workflowEvidenceDirectory(workflow);
  mkdirSync(directory, { recursive: true });
  const screenshot = `${step}.png`;
  const path = join(directory, screenshot);
  if (focusSelector !== null) {
    assert.equal(typeof focusSelector, 'string');
    assert.ok(focusSelector.length > 0 && focusSelector.length <= 200, 'focus selector must be bounded');
    const focused = await browser.execute((selector) => {
      const node = document.querySelector(selector);
      if (node === null) return false;
      node.scrollIntoView({ block: 'center', inline: 'nearest' });
      return true;
    }, focusSelector);
    assert.ok(focused, `workflow evidence focus target is missing: ${focusSelector}`);
    await browser.pause(100);
  }
  // Journeys legitimately use Ctrl+A inside timeline/editing controls. WebDriver can leave a
  // document selection painted after the control has handled the shortcut, producing screenshots
  // covered in grey selection rectangles that no customer sees. Evidence captures presentation,
  // so clear only that transient browser selection; do not blur controls or alter product state.
  await browser.execute(() => window.getSelection()?.removeAllRanges());
  // Capture the settled surface, not an intermediate opacity/blur frame from a modal or section
  // transition. This does not wait on product state; journeys establish that before calling us.
  await browser.pause(300);
  const state = await visibleState();
  await browser.saveScreenshot(path);
  assert.ok(statSync(path).size > 1_000, `workflow screenshot is implausibly small: ${path}`);

  const manifest = readManifest(workflow);
  const record = {
    step,
    description: description.trim(),
    screenshot,
    state,
    details,
  };
  manifest.steps = manifest.steps.filter((candidate) => candidate.step !== step);
  manifest.steps.push(record);
  manifest.steps.sort((left, right) => left.step.localeCompare(right.step));
  writeIndex(manifest);
  return record;
};

export const copyWorkflowArtifact = ({ workflow, name, source, description }) => {
  safeSegment(name, 'artifact name');
  assert.ok(existsSync(source), `workflow artifact does not exist: ${source}`);
  const directory = workflowEvidenceDirectory(workflow);
  mkdirSync(directory, { recursive: true });
  const base = basename(source);
  const extension = base.includes('.') ? base.slice(base.lastIndexOf('.')) : '';
  const file = `${name}${extension}`;
  copyFileSync(source, join(directory, file));
  const manifest = readManifest(workflow);
  manifest.artifacts = manifest.artifacts.filter((artifact) => artifact.name !== name);
  manifest.artifacts.push({ name, file, description });
  manifest.artifacts.sort((left, right) => left.name.localeCompare(right.name));
  writeIndex(manifest);
  return join(directory, file);
};
