import { invokeDesktopRaw } from './desktopRuntime';
import { isDesktopRuntime } from './runtimeEnvironment';
import { exportGeneratedBlob } from './generatedFileExportService';

vi.mock('./desktopRuntime', () => ({
  invokeDesktop: vi.fn(),
  invokeDesktopRaw: vi.fn(),
}));
vi.mock('./runtimeEnvironment', () => ({ isDesktopRuntime: vi.fn(() => true) }));

test('exports generated bytes with a type-matched sanitized name', async () => {
  isDesktopRuntime.mockReturnValue(true);
  invokeDesktopRaw.mockResolvedValue(true);
  const blob = new Blob(['RIFF0000WAVEdata'], { type: 'audio/wav' });

  await expect(exportGeneratedBlob(blob, '../background music.webm')).resolves.toBe(true);
  expect(invokeDesktopRaw).toHaveBeenCalledWith(
    'generated_file_export',
    expect.any(Uint8Array),
    {
      'x-osg-content-type': 'audio/wav',
      'x-osg-file-name': 'background_music.wav',
    }
  );
});

test('rejects unsupported or oversized inputs before IPC', async () => {
  invokeDesktopRaw.mockClear();
  await expect(exportGeneratedBlob(new Blob(['x'], { type: 'text/plain' }), 'x.txt'))
    .rejects.toThrow(/invalid/i);
  expect(invokeDesktopRaw).not.toHaveBeenCalled();
});
