import { createNativeGeminiImage } from './nativeGeminiImage';

vi.mock('@tauri-apps/api/core', () => ({ Channel: class {} }));

const CREDENTIAL_A = '01890f39-7b62-7c4e-8c9a-000000000301';
const CREDENTIAL_B = '01890f39-7b62-7c4e-8c9a-000000000302';
const REFERENCE_ID = '01890f39-7b62-7c4e-8c9a-000000000303';
const JOB_A = '01890f39-7b62-7c4e-8c9a-000000000304';
const JOB_B = '01890f39-7b62-7c4e-8c9a-000000000305';
const PROJECT_A = '01890f39-7b62-7c4e-8c9a-000000000306';
const PROJECT_B = '01890f39-7b62-7c4e-8c9a-000000000307';
const ARTIFACT_A = '01890f39-7b62-7c4e-8c9a-000000000308';
const ARTIFACT_B = '01890f39-7b62-7c4e-8c9a-000000000309';
const PLAYBACK_A = '4a8672f4-6e8f-4a16-8e4a-36b7d20fdb11';
const PLAYBACK_B = '9cb6df97-92c6-4f6d-8717-c2a7acb74a12';
const REFERENCE_PLAYBACK = 'c89ea814-1749-4c3b-8507-4c457df2ef30';
const TOKEN = 'a'.repeat(64);
const REFERENCE_PLAYBACK_URL = `http://127.0.0.1:43210/asset/${REFERENCE_PLAYBACK}?token=${TOKEN}`;

const snapshot = (id, state, sequence = 1) => ({
  id,
  kind: 'generateImage',
  state,
  progress: { basisPoints: state === 'succeeded' ? 10_000 : 0 },
  sequence,
});

const descriptor = (artifactId = ARTIFACT_A, projectId = PROJECT_A, mimeType = 'image/png') => ({
  artifactId,
  projectId,
  mimeType,
  sizeBytes: 4,
  createdAtMs: 1_700_000_000_000,
});

const playable = ({
  artifactId = ARTIFACT_A,
  projectId = PROJECT_A,
  playbackId = PLAYBACK_A,
  mimeType = 'image/png',
} = {}) => ({
  artifact: descriptor(artifactId, projectId, mimeType),
  playback: {
    id: playbackId,
    playbackUrl: `http://127.0.0.1:43210/asset/${playbackId}?token=${TOKEN}`,
    mimeType,
    byteLength: 4,
  },
});

class FakeChannel {
  onmessage = null;
}

const createHarness = ({
  invokeImplementation,
  importImageImplementation,
  resolveProjectImplementation,
  credentials = [CREDENTIAL_A],
} = {}) => {
  let activeIndex = 0;
  let activeCache = 'cache-a';
  const importImage = vi.fn(importImageImplementation ?? (async () => ({
    assetId: REFERENCE_ID,
    mimeType: 'image/png',
    sizeBytes: 16,
  })));
  const releaseImage = vi.fn().mockResolvedValue(true);
  const rotateCredential = vi.fn(async () => {
    activeIndex += 1;
  });
  const invokeCommand = vi.fn(invokeImplementation ?? (async (command, args) => {
    if (command === 'generated_image_playback_release') return true;
    if (command === 'gemini_image_complete') {
      return snapshot(args.request.jobId, 'succeeded', 2);
    }
    if (command !== 'gemini_image_start') throw new Error(`unexpected command ${command}`);
    queueMicrotask(() => {
      args.onEvent.onmessage({
        event: 'prepared',
        job: snapshot(JOB_A, 'running'),
        image: playable(),
      });
    });
    return snapshot(JOB_A, 'running');
  }));
  const cancel = vi.fn().mockResolvedValue(snapshot(JOB_A, 'cancelled', 2));
  const getCacheId = vi.fn(() => activeCache);
  const resolveProject = vi.fn(resolveProjectImplementation ?? (async (cacheId) => ({
    cacheId,
    projectId: cacheId === 'cache-a' ? PROJECT_A : PROJECT_B,
  })));
  const service = createNativeGeminiImage({
    prepareCredentials: vi.fn().mockResolvedValue(undefined),
    getCredentialId: vi.fn(() => credentials[activeIndex] ?? null),
    getCredentialSnapshot: vi.fn(() => ({
      gemini: { availableCredentialIds: credentials },
    })),
    rotateCredential,
    importImage,
    releaseImage,
    getCacheId,
    resolveProject,
    invokeCommand,
    ChannelConstructor: FakeChannel,
    cancel,
    isNativeRuntime: () => true,
  });
  return {
    service,
    importImage,
    releaseImage,
    rotateCredential,
    getCacheId,
    resolveProject,
    invokeCommand,
    cancel,
    setActiveProject: (projectId) => {
      activeCache = projectId === PROJECT_A ? 'cache-a' : 'cache-b';
    },
  };
};

test('returns only a project-owned artifact capability and never requests generated bytes', async () => {
  const harness = createHarness();
  const result = await harness.service.generate({
    referencePlaybackUrl: REFERENCE_PLAYBACK_URL,
    prompt: 'Expand this cover into a landscape image',
  });

  expect(result).toEqual({
    image: playable(),
    job: snapshot(JOB_A, 'succeeded', 2),
  });
  expect(harness.invokeCommand).toHaveBeenCalledWith('gemini_image_start', {
    request: {
      credentialId: CREDENTIAL_A,
      model: 'gemini-3.1-flash-image',
      prompt: expect.any(String),
      referenceAssetId: REFERENCE_ID,
      projectId: PROJECT_A,
    },
    onEvent: expect.any(FakeChannel),
  });
  expect(harness.invokeCommand).toHaveBeenCalledWith('gemini_image_complete', {
    request: {
      jobId: JOB_A,
      projectId: PROJECT_A,
      artifactId: ARTIFACT_A,
      playbackId: PLAYBACK_A,
    },
  });
  const serialized = JSON.stringify(result);
  expect(serialized).not.toMatch(/(?:base64|data:image|"bytes"|file:|[A-Za-z]:\\)/i);
  expect(harness.invokeCommand.mock.calls[0][1]).not.toHaveProperty('onImage');
  expect(harness.importImage).toHaveBeenCalledWith(REFERENCE_PLAYBACK_URL, PROJECT_A);
  expect(harness.releaseImage).toHaveBeenCalledWith(REFERENCE_ID);
});

test('rotates credentials only after a sanitized credential failure', async () => {
  let startCall = 0;
  const harness = createHarness({
    credentials: [CREDENTIAL_A, CREDENTIAL_B],
    invokeImplementation: async (command, args) => {
      if (command === 'generated_image_playback_release') return true;
      if (command === 'gemini_image_complete') {
        return snapshot(args.request.jobId, 'succeeded', 2);
      }
      if (command !== 'gemini_image_start') throw new Error(`unexpected command ${command}`);
      startCall += 1;
      const id = startCall === 1 ? JOB_A : JOB_B;
      queueMicrotask(() => {
        if (startCall === 1) {
          args.onEvent.onmessage({
            event: 'failed',
            job: snapshot(id, 'failed', 2),
            error: { code: 'geminiRateLimited', message: 'fixed host message' },
          });
        } else {
          args.onEvent.onmessage({
            event: 'prepared',
            job: snapshot(id, 'running'),
            image: playable(),
          });
        }
      });
      return snapshot(id, 'running');
    },
  });

  await expect(harness.service.generate({
    referencePlaybackUrl: REFERENCE_PLAYBACK_URL,
    prompt: 'Generate',
  })).resolves.toMatchObject({ image: playable() });
  expect(harness.rotateCredential).toHaveBeenCalledWith({
    cooldownCredentialId: CREDENTIAL_A,
  });
  expect(harness.invokeCommand.mock.calls[1][1].request.credentialId).toBe(CREDENTIAL_B);
});

test.each([
  ['raw byte payload', new Uint8Array([1, 2, 3])],
  ['wrong project', {
    event: 'prepared',
    job: snapshot(JOB_A, 'running'),
    image: playable({ projectId: PROJECT_B }),
  }],
  ['stale run', {
    event: 'prepared',
    job: snapshot(JOB_B, 'running'),
    image: playable(),
  }],
  ['unknown field', {
    event: 'prepared',
    job: snapshot(JOB_A, 'running'),
    image: { ...playable(), bytes: [1, 2, 3] },
  }],
])('rejects %s before exposing a generated result', async (_label, payload) => {
  const harness = createHarness({
    invokeImplementation: async (command, args) => {
      if (command !== 'gemini_image_start') return true;
      queueMicrotask(() => args.onEvent.onmessage(payload));
      return snapshot(JOB_A, 'running');
    },
  });

  await expect(harness.service.generate({
    referencePlaybackUrl: REFERENCE_PLAYBACK_URL,
    prompt: 'Generate',
  })).rejects.toMatchObject({ code: 'invalidGeminiImageResponse' });
  expect(harness.cancel).toHaveBeenCalledWith(JOB_A);
  expect(harness.releaseImage).toHaveBeenCalledWith(REFERENCE_ID);
});

test('rejects a project switch after completion and releases the stale capability', async () => {
  const harness = createHarness({
    invokeImplementation: async (command, args) => {
      if (command === 'generated_image_playback_release') return true;
      if (command === 'gemini_image_complete') {
        return snapshot(args.request.jobId, 'succeeded', 2);
      }
      queueMicrotask(() => {
        harness.setActiveProject(PROJECT_B);
        args.onEvent.onmessage({
          event: 'prepared',
          job: snapshot(JOB_A, 'running'),
          image: playable(),
        });
      });
      return snapshot(JOB_A, 'running');
    },
  });

  await expect(harness.service.generate({
    referencePlaybackUrl: REFERENCE_PLAYBACK_URL,
    prompt: 'Generate',
  })).rejects.toMatchObject({ code: 'staleGeminiImageResult' });
  expect(harness.invokeCommand).toHaveBeenCalledWith('generated_image_playback_release', {
    request: {
      projectId: PROJECT_A,
      artifactId: ARTIFACT_A,
      playbackId: PLAYBACK_A,
    },
  });
});

test('list resolve export delete clear and release use only bounded opaque identities', async () => {
  const calls = [];
  const harness = createHarness({
    invokeImplementation: async (command, args) => {
      calls.push([command, args]);
      if (command === 'generated_image_list') {
        return [descriptor(ARTIFACT_A), descriptor(ARTIFACT_B)];
      }
      if (command === 'generated_image_resolve') {
        return args.request.artifactId === ARTIFACT_A
          ? playable()
          : playable({ artifactId: ARTIFACT_B, playbackId: PLAYBACK_B });
      }
      if (command === 'generated_image_export') return true;
      if (command === 'generated_image_delete') return true;
      if (command === 'generated_image_clear') return 2;
      if (command === 'generated_image_playback_release') return true;
      throw new Error('unexpected command');
    },
  });

  const loaded = await harness.service.load(PROJECT_A);
  expect(loaded).toHaveLength(2);
  await expect(harness.service.exportImage({
    projectId: PROJECT_A,
    artifactId: ARTIFACT_A,
    suggestedName: 'background-1.png',
  })).resolves.toBe(true);
  await expect(harness.service.deleteImage({
    projectId: PROJECT_A,
    artifactId: ARTIFACT_A,
  })).resolves.toBe(true);
  await expect(harness.service.clear(PROJECT_A)).resolves.toBe(2);
  await expect(harness.service.releasePlayback(loaded[0])).resolves.toBe(true);

  expect(JSON.stringify(calls)).not.toMatch(/(?:base64|data:image|"bytes"|file:|[A-Za-z]:\\)/i);
});

test('stale rendered project identities cannot export delete or clear another active project', async () => {
  const harness = createHarness();
  harness.setActiveProject(PROJECT_B);

  await expect(harness.service.exportImage({
    projectId: PROJECT_A,
    artifactId: ARTIFACT_A,
    suggestedName: 'background-1.png',
  })).rejects.toMatchObject({ code: 'staleGeminiImageProject' });
  await expect(harness.service.deleteImage({
    projectId: PROJECT_A,
    artifactId: ARTIFACT_A,
  })).rejects.toMatchObject({ code: 'staleGeminiImageProject' });
  await expect(harness.service.clear(PROJECT_A))
    .rejects.toMatchObject({ code: 'staleGeminiImageProject' });

  expect(harness.invokeCommand.mock.calls.filter(([command]) => [
    'generated_image_export',
    'generated_image_delete',
    'generated_image_clear',
  ].includes(command))).toHaveLength(0);
  await expect(harness.service.releasePlayback(playable())).resolves.toBe(true);
  expect(harness.invokeCommand).toHaveBeenCalledWith('generated_image_playback_release', {
    request: {
      projectId: PROJECT_A,
      artifactId: ARTIFACT_A,
      playbackId: PLAYBACK_A,
    },
  });
});

test.each([
  [
    'export',
    (service) => service.exportImage({
      projectId: PROJECT_A,
      artifactId: ARTIFACT_A,
      suggestedName: 'background-1.png',
    }),
    'generated_image_export',
  ],
  [
    'delete',
    (service) => service.deleteImage({ projectId: PROJECT_A, artifactId: ARTIFACT_A }),
    'generated_image_delete',
  ],
  ['clear', (service) => service.clear(PROJECT_A), 'generated_image_clear'],
])('a cache A to B switch during awaited project resolution blocks %s IPC', async (
  _operation,
  runMutation,
  forbiddenCommand
) => {
  let resolveLookup;
  const harness = createHarness({
    resolveProjectImplementation: (cacheId) => new Promise((resolve) => {
      resolveLookup = () => resolve({ cacheId, projectId: PROJECT_A });
    }),
  });

  const mutation = runMutation(harness.service);
  await vi.waitFor(() => expect(resolveLookup).toBeTypeOf('function'));
  harness.setActiveProject(PROJECT_B);
  resolveLookup();

  await expect(mutation).rejects.toMatchObject({ code: 'staleGeminiImageProject' });
  expect(harness.invokeCommand.mock.calls.some(([command]) => command === forbiddenCommand))
    .toBe(false);
});

test('the cache is reread synchronously immediately before destructive IPC', async () => {
  const getCacheId = vi.fn()
    .mockReturnValueOnce('cache-a')
    .mockReturnValueOnce('cache-a')
    .mockReturnValue('cache-b');
  const invokeCommand = vi.fn();
  const service = createNativeGeminiImage({
    getCacheId,
    resolveProject: vi.fn().mockResolvedValue({ cacheId: 'cache-a', projectId: PROJECT_A }),
    invokeCommand,
    isNativeRuntime: () => true,
  });

  await expect(service.deleteImage({
    projectId: PROJECT_A,
    artifactId: ARTIFACT_A,
  })).rejects.toMatchObject({ code: 'staleGeminiImageProject' });
  expect(invokeCommand).not.toHaveBeenCalled();
  expect(getCacheId).toHaveBeenCalledTimes(3);
});

test.each([
  '../background.png',
  'background..png',
  'background.gif',
  '배경.png',
  'background.png.exe',
])('rejects malformed export name %s before IPC', async (suggestedName) => {
  const harness = createHarness();
  await expect(harness.service.exportImage({
    projectId: PROJECT_A,
    artifactId: ARTIFACT_A,
    suggestedName,
  })).rejects.toMatchObject({ code: 'invalidGeneratedImageRequest' });
  expect(harness.invokeCommand).not.toHaveBeenCalled();
});

test('a malformed list response releases already-created capabilities and fails closed', async () => {
  const harness = createHarness({
    invokeImplementation: async (command, args) => {
      if (command === 'generated_image_list') {
        return [descriptor(ARTIFACT_A), descriptor(ARTIFACT_B)];
      }
      if (command === 'generated_image_resolve' && args.request.artifactId === ARTIFACT_A) {
        return playable();
      }
      if (command === 'generated_image_resolve') {
        return { ...playable({ artifactId: ARTIFACT_B }), rawBytes: [1] };
      }
      if (command === 'generated_image_playback_release') return true;
      throw new Error('unexpected command');
    },
  });

  await expect(harness.service.load(PROJECT_A))
    .rejects.toMatchObject({ code: 'invalidGeminiImageResponse' });
  expect(harness.invokeCommand).toHaveBeenCalledWith('generated_image_playback_release', {
    request: {
      projectId: PROJECT_A,
      artifactId: ARTIFACT_A,
      playbackId: PLAYBACK_A,
    },
  });
});

test('a pre-aborted request performs no project lookup, import, or native invocation', async () => {
  const harness = createHarness();
  const controller = new AbortController();
  controller.abort();

  await expect(harness.service.generate({
    referencePlaybackUrl: REFERENCE_PLAYBACK_URL,
    prompt: 'Generate',
    signal: controller.signal,
  })).rejects.toMatchObject({ name: 'AbortError' });
  expect(harness.getCacheId).not.toHaveBeenCalled();
  expect(harness.importImage).not.toHaveBeenCalled();
  expect(harness.invokeCommand).not.toHaveBeenCalled();
});

test('a project switch during native reference transfer releases the imported reference', async () => {
  let resolveImport;
  const harness = createHarness({
    importImageImplementation: () => new Promise((resolve) => {
      resolveImport = resolve;
    }),
  });
  const generation = harness.service.generate({
    referencePlaybackUrl: REFERENCE_PLAYBACK_URL,
    prompt: 'Generate',
  });
  await vi.waitFor(() => expect(resolveImport).toBeTypeOf('function'));
  harness.setActiveProject(PROJECT_B);
  resolveImport({ assetId: REFERENCE_ID, mimeType: 'image/png', sizeBytes: 16 });

  await expect(generation).rejects.toMatchObject({ code: 'staleGeminiImageProject' });
  expect(harness.releaseImage).toHaveBeenCalledWith(REFERENCE_ID);
  expect(harness.invokeCommand).not.toHaveBeenCalled();
});

test('production project lookup resolves the exact current cache instead of persisted last-active state', async () => {
  const resolveProject = vi.fn().mockResolvedValue({ cacheId: 'cache-b', projectId: PROJECT_B });
  const service = createNativeGeminiImage({
    getCacheId: () => 'cache-b',
    resolveProject,
    isNativeRuntime: () => true,
  });

  await expect(service.getActiveProjectId()).resolves.toBe(PROJECT_B);
  expect(resolveProject).toHaveBeenCalledWith('cache-b', { create: true });
});

test('completion that wins an abort race returns its committed capability for exact release', async () => {
  let channelArgs;
  let resolveCompletion;
  const completion = new Promise((resolve) => { resolveCompletion = resolve; });
  const harness = createHarness({
    invokeImplementation: async (command, args) => {
      if (command === 'gemini_image_start') {
        channelArgs = args;
        return snapshot(JOB_A, 'running');
      }
      if (command === 'gemini_image_complete') return completion;
      if (command === 'generated_image_playback_release') return true;
      throw new Error(`unexpected command ${command}`);
    },
  });
  const controller = new AbortController();
  const generation = harness.service.generate({
    referencePlaybackUrl: REFERENCE_PLAYBACK_URL,
    prompt: 'Generate',
    signal: controller.signal,
  });
  await vi.waitFor(() => expect(channelArgs).toBeDefined());
  const prepared = {
    event: 'prepared',
    job: snapshot(JOB_A, 'running'),
    image: playable(),
  };
  channelArgs.onEvent.onmessage(prepared);
  await vi.waitFor(() => expect(harness.invokeCommand)
    .toHaveBeenCalledWith('gemini_image_complete', expect.any(Object)));

  controller.abort();
  resolveCompletion(snapshot(JOB_A, 'succeeded', 2));
  const result = await generation;
  expect(result.job.state).toBe('succeeded');
  expect(harness.cancel).toHaveBeenCalledWith(JOB_A);
  expect(harness.invokeCommand.mock.calls.filter(([command]) => (
    command === 'generated_image_playback_release'
  ))).toHaveLength(0);
  await harness.service.releasePlayback(result.image);
  expect(harness.invokeCommand).toHaveBeenCalledWith(
    'generated_image_playback_release',
    {
      request: {
        projectId: PROJECT_A,
        artifactId: ARTIFACT_A,
        playbackId: PLAYBACK_A,
      },
    }
  );
  channelArgs.onEvent.onmessage(prepared);
  await Promise.resolve();
  expect(harness.invokeCommand.mock.calls.filter(([command]) => (
    command === 'generated_image_playback_release'
  ))).toHaveLength(1);
});

test('cancellation that wins during acknowledgement rejects and releases the capability once', async () => {
  let channelArgs;
  let rejectCompletion;
  const completion = new Promise((_resolve, reject) => { rejectCompletion = reject; });
  const harness = createHarness({
    invokeImplementation: async (command, args) => {
      if (command === 'gemini_image_start') {
        channelArgs = args;
        return snapshot(JOB_A, 'running');
      }
      if (command === 'gemini_image_complete') return completion;
      if (command === 'generated_image_playback_release') return true;
      throw new Error(`unexpected command ${command}`);
    },
  });
  const controller = new AbortController();
  const generation = harness.service.generate({
    referencePlaybackUrl: REFERENCE_PLAYBACK_URL,
    prompt: 'Generate',
    signal: controller.signal,
  });
  await vi.waitFor(() => expect(channelArgs).toBeDefined());
  channelArgs.onEvent.onmessage({
    event: 'prepared',
    job: snapshot(JOB_A, 'running'),
    image: playable(),
  });
  await vi.waitFor(() => expect(harness.invokeCommand)
    .toHaveBeenCalledWith('gemini_image_complete', expect.any(Object)));

  controller.abort();
  rejectCompletion(Object.assign(new Error('cancellation won'), { code: 'jobConflict' }));

  await expect(generation).rejects.toMatchObject({ name: 'AbortError' });
  expect(harness.cancel).toHaveBeenCalledWith(JOB_A);
  await vi.waitFor(() => expect(harness.invokeCommand.mock.calls.filter(([command]) => (
    command === 'generated_image_playback_release'
  ))).toHaveLength(1));
});

test('a prepared capability arriving after an early abort is never acknowledged and is released once', async () => {
  let channelArgs;
  let resolveStart;
  const harness = createHarness({
    invokeImplementation: async (command, args) => {
      if (command === 'gemini_image_start') {
        channelArgs = args;
        return new Promise((resolve) => { resolveStart = resolve; });
      }
      if (command === 'generated_image_playback_release') return true;
      throw new Error(`unexpected command ${command}`);
    },
  });
  const controller = new AbortController();
  const generation = harness.service.generate({
    referencePlaybackUrl: REFERENCE_PLAYBACK_URL,
    prompt: 'Generate',
    signal: controller.signal,
  });
  await vi.waitFor(() => expect(channelArgs).toBeDefined());
  controller.abort();
  channelArgs.onEvent.onmessage({
    event: 'prepared',
    job: snapshot(JOB_A, 'running'),
    image: playable(),
  });
  resolveStart(snapshot(JOB_A, 'running'));

  await expect(generation).rejects.toMatchObject({ name: 'AbortError' });
  expect(harness.invokeCommand.mock.calls.filter(([command]) => (
    command === 'gemini_image_complete'
  ))).toHaveLength(0);
  await vi.waitFor(() => expect(harness.invokeCommand.mock.calls.filter(([command]) => (
    command === 'generated_image_playback_release'
  ))).toHaveLength(1));
});

test('a lost completion response retries the exact acknowledgement without duplicate release', async () => {
  let completionCalls = 0;
  const harness = createHarness({
    invokeImplementation: async (command, args) => {
      if (command === 'gemini_image_complete') {
        completionCalls += 1;
        if (completionCalls === 1) throw new Error('response lost after commit');
        return snapshot(args.request.jobId, 'succeeded', 2);
      }
      if (command === 'generated_image_playback_release') return true;
      queueMicrotask(() => args.onEvent.onmessage({
        event: 'prepared',
        job: snapshot(JOB_A, 'running'),
        image: playable(),
      }));
      return snapshot(JOB_A, 'running');
    },
  });

  await expect(harness.service.generate({
    referencePlaybackUrl: REFERENCE_PLAYBACK_URL,
    prompt: 'Generate',
  })).resolves.toMatchObject({ job: { state: 'succeeded' } });
  expect(completionCalls).toBe(2);
  expect(harness.invokeCommand.mock.calls.filter(([command]) => (
    command === 'generated_image_playback_release'
  ))).toHaveLength(0);
});

test('a failed completion acknowledgement releases the prepared playback exactly once', async () => {
  const harness = createHarness({
    invokeImplementation: async (command, args) => {
      if (command === 'generated_image_playback_release') return true;
      if (command === 'gemini_image_complete') {
        throw Object.assign(new Error('ack failed'), { code: 'nativeGeminiImageFailed' });
      }
      queueMicrotask(() => args.onEvent.onmessage({
        event: 'prepared',
        job: snapshot(JOB_A, 'running'),
        image: playable(),
      }));
      return snapshot(JOB_A, 'running');
    },
  });

  await expect(harness.service.generate({
    referencePlaybackUrl: REFERENCE_PLAYBACK_URL,
    prompt: 'Generate',
  })).rejects.toMatchObject({ code: 'nativeGeminiImageFailed' });
  expect(harness.invokeCommand.mock.calls.filter(([command]) => (
    command === 'generated_image_playback_release'
  ))).toHaveLength(1);
});
