import { generateNativeGeminiImage } from '../../platform/nativeGeminiImage';
import { runNativeGeminiText } from '../../platform/nativeGeminiText';
import { toBase64 } from '../../utils/fileUtils';
import {
  generateBackgroundImage,
  generateBackgroundPrompt,
} from './imageGenerationService';

vi.mock('../../platform/nativeGeminiImage', () => ({
  generateNativeGeminiImage: vi.fn(),
}));
vi.mock('../../platform/nativeGeminiText', () => ({
  runNativeGeminiText: vi.fn(),
}));
vi.mock('../../utils/fileUtils', () => ({ toBase64: vi.fn() }));

beforeEach(() => {
  vi.clearAllMocks();
  localStorage.clear();
  localStorage.setItem('gemini_api_key', 'must-not-be-read-or-sent');
  runNativeGeminiText.mockResolvedValue({ text: '  cinematic night sky  ' });
  generateNativeGeminiImage.mockResolvedValue({
    bytes: new Uint8Array([0x89, 0x50, 0x4e, 0x47]),
    mimeType: 'image/png',
  });
  toBase64.mockResolvedValue('generated-image-base64');
  global.fetch = vi.fn(() => {
    throw new Error('desktop image generation must not use browser fetch');
  });
});

afterAll(() => {
  delete global.fetch;
});

test('generates the background prompt through the vault-backed native text job', async () => {
  const getItem = vi.spyOn(Storage.prototype, 'getItem');
  await expect(generateBackgroundPrompt('lyrics here', 'Song')).resolves.toBe('cinematic night sky');
  expect(runNativeGeminiText).toHaveBeenCalledWith(expect.objectContaining({
    task: 'analyzeSubtitles',
    model: 'gemini-3.5-flash-lite',
    prompt: expect.stringContaining('lyrics here'),
  }));
  expect(getItem).not.toHaveBeenCalledWith('gemini_api_key');
  getItem.mockRestore();
});

test('imports album art and receives generated bytes without provider transport in the WebView', async () => {
  const albumArt = `data:image/png;base64,${btoa('\x89PNG\r\n\x1a\ncover')}`;

  await expect(generateBackgroundImage('decorate this', albumArt)).resolves.toEqual({
    data: 'generated-image-base64',
    mime_type: 'image/png',
  });
  expect(generateNativeGeminiImage).toHaveBeenCalledWith(expect.objectContaining({
    referenceBlob: expect.any(Blob),
    prompt: expect.stringContaining('decorate this'),
    model: 'gemini-3.1-flash-image',
  }));
  expect(global.fetch).not.toHaveBeenCalled();
});

test('migrates a retired image model selection to the sole video-capable image model', async () => {
  localStorage.setItem('background_image_model', 'gemini-2.5-flash-image');
  const albumArt = `data:image/png;base64,${btoa('\x89PNG\r\n\x1a\ncover')}`;

  await generateBackgroundImage('decorate this', albumArt);
  expect(generateNativeGeminiImage).toHaveBeenCalledWith(expect.objectContaining({
    model: 'gemini-3.1-flash-image',
  }));
});
